In [5]:
import numpy as np

# NumPy Arrays    

In [2]:
my_list = [1,2,3]

np.array(my_list)

array([1, 2, 3])

In [3]:
# we can make matrix out of it:

my_mat = [[1,2,3], [4,5,6], [7,8,9]]

np.array(my_mat) # it converted the list of lists into a matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# to create a numPy array out of nowhere:

print(np.arange(0,10)) # see again 10 not included.

print(np.arange(0,10, 2)) # Gives a step of 2

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [4]:
# Generating an arrays of all zeros:

print(np.zeros(3))

# Similarly, an array of 1s

print(np.ones(3))
print("########")

print(np.zeros((3, 5))) # we can give two numbers to get a matrix

# simillarly works for np.ones

print(np.linspace(1,100, 7)) #  tell it from, to and number of numbers we want as an output.

[0. 0. 0.]
[1. 1. 1.]
########
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[  1.   17.5  34.   50.5  67.   83.5 100. ]


In [7]:
# creating an identity matrix using numPy:

print(np.eye(4)) # creates a 4 * 4 identity matrix.

print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# Random number generator - uniformly distributed from zero to one.

print(np.random.rand(5))

# we can get a matrix also
print(np.random.rand(5,5))


[0.7829773  0.21241021 0.93297237 0.16453095 0.95599745]
[[0.96600806 0.52541421 0.06960935 0.4275335  0.79383697]
 [0.61576834 0.22724568 0.5847492  0.90714821 0.78490282]
 [0.21788131 0.78546517 0.67112801 0.9664908  0.33150259]
 [0.12700509 0.92026771 0.96181796 0.42397386 0.16562967]
 [0.5518886  0.26742784 0.5353509  0.91876467 0.77533101]]


In [33]:

# to get numbers from a stndard normal distribution:


np.random.randn(5)

array([ 0.23217585, -0.84829032, -1.59869027, -0.24293696, -0.55697781])

In [5]:
# get a random integer

np.random.randint(0,100) # will generate a random integer between zero(included) and 100(not included).

# we can feed im the number of random integer we want. - as the third argument.

# we can reshape an array by using the reshape function:

arr = np.random.randint(0,786,10)

print(arr)
arr.reshape(5,2)


[254  99 537 209 133 694 622 109 727 336]


array([[254,  99],
       [537, 209],
       [133, 694],
       [622, 109],
       [727, 336]])

In [7]:

# we can get the maximum value of an array:

arr.max() # of course works for min also.

# we can get the index location of the max and the minimum value:

arr.argmax()

8

In [12]:
# we can see the shape of the array by:
print(arr)

arr = arr.reshape(5,2)

arr.shape

[[254  99]
 [537 209]
 [133 694]
 [622 109]
 [727 336]]


(5, 2)

# NumPy Selection and Indexing:

In [18]:
arr = np.arange(0,11)

print(arr)

arr[3:6]

arr[5:] # takes everything from 5 till end (including the index 5 and including the end)

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 5,  6,  7,  8,  9, 10])

In [25]:
# A very interesting thing to note here:
arr = np.arange(0,11)

print(arr)

slice_of_arr = arr[:6]
slice_of_arr[:] = 0 # please dont do slice_of-arr = 0
print(arr)

# thr interesting thing to note here s: upon modifying the slice of arr, the full arr got changed.
# So, its just viewing when we subset, it doesnt make a newvariable by itself.
# seriously a fucked up language.

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  0  0  0  0  0  6  7  8  9 10]


In [26]:
# the good news is: One can make a copy like this;
arr_copy = arr.copy()



In [11]:
0# Indexing from a 2d array:
np_arr = np.array([[10,20,30],[3,2,1]])

print(np_arr)

# keep in mind, this indexing is not same as R indexing.

print(np_arr[1][1]) # it took the arr  at index 1 i.e. [3,2,1] and then took the number at index 1 in that arr. that is 2 

# there is other indexing method, that is same as that of R.

print(np_arr[1,2]) # again, indexing starts from 0.

[[10 20 30]
 [ 3  2  1]]
2
1


In [14]:
# Conditional Selection:

arr = np.arange(1,11)

bol_arr = arr > 5

arr[bol_arr]
# OR
arr[arr > 5]




array([ 6,  7,  8,  9, 10])

NumPy Operation

In [15]:
# We can add/mupliply/divide two arrays together, like we do in R with vectors.
 
print(arr)

arr2 = arr

arr = arr + 10

print(arr)
print(arr2)

# Look at the amazing thing here:
# here when I changed arr, arr2 diddnt change.
# So, its somewhat like vectors in R only.

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10]


In [49]:
# we can take sq root of everything in array:

np.sqrt(arr)

# can take exponential also:
np.exp(arr)
# take a log:
np.log(arr)
# take sin:
np.sin(arr)


array([6.39843494e+17, 1.73927494e+18, 4.72783947e+18, 1.28516001e+19,
       3.49342711e+19, 9.49611942e+19, 2.58131289e+20, 7.01673591e+20,
       1.90734657e+21, 5.18470553e+21])